export const backgroundImages: any[]= [
  { "value": "", "label": "Faction" },
  { "value": "space-marines", "label": "Space Marines" },
  { "value": "grey-knights", "label": "Grey Knights" },
  { "value": "imperial-guard", "label": "Imperial Guard" },
  { "value": "forge-world", "label": "Forge World" },
  { "value": "ecclesiarchy", "label": "Ecclesiarchy" },
  { "value": "talons-of-the-emperor", "label": "Talons of the Emperor" },
  { "value": "thousand-sons", "label": "Thousand Sons" },
  { "value": "kommandos", "label": "Kommandos" },
  { "value": "death-guard", "label": "Death Guard" },
  { "value": "traitor-space-marines", "label": "Traitor Space Marines" },
  { "value": "chaos-daemons", "label": "Chaos Daemons" },
  { "value": "craftworlds", "label": "Craftworlds" },
  { "value": "veteran-guardsman", "label": "Veteran Guardsman" },
  { "value": "troupes", "label": "Troupes" },
  { "value": "commorrites", "label": "Commorrites" },
  { "value": "greenskins", "label": "Greenskins" },
  { "value": "hunter-cadres", "label": "Hunter Cadres" },
  { "value": "tomb-worlds", "label": "Tomb Worlds" },
  { "value": "hive-fleets", "label": "Hive Fleets" },
  { "value": "cadre-mercenary", "label": "Cadre Mercenary" },
  { "value": "brood-covens", "label": "Brood Covens" }
]
